language: r
sudo: required
dist: trusty
bioc_required: true
cache: packages
install:
 - R -e 'install.packages("devtools")'
 - R -e 'setRepositories(ind = 1:2); devtools::install(dependencies = T, upgrade = T)'
warnings_are_errors: false
r_check_args: "--no-tests --no-manual --no-vignettes --no-build-vignettes --no-examples"
r_build_args: "--no-build-vignettes"
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_="FALSE"

